### ISSUE TITLE
doesn't seem to compile with ghc 8.4

### ISSUE THREAD

**Issue by shmish111** [jyp/glpk-hs#12]
I think some `Semigroup` instances are required
```
    /private/var/folders/gt/tp3vtxxs77b960txrxxndfqm0000gn/T/stack26835/glpk-hs-0.5/Data/LinearProgram/Types.hs:16:10: error:
        • No instance for (Semigroup VarKind)
            arising from the superclasses of an instance declaration
        • In the instance declaration for ‘Monoid VarKind’
       |
    16 | instance Monoid VarKind where
       |          ^^^^^^^^^^^^^^

    /private/var/folders/gt/tp3vtxxs77b960txrxxndfqm0000gn/T/stack26835/glpk-hs-0.5/Data/LinearProgram/Types.hs:39:10: error:
        • Could not deduce (Semigroup (Bounds a))
            arising from the superclasses of an instance declaration
          from the context: Ord a
            bound by the instance declaration
            at Data/LinearProgram/Types.hs:39:10-35
        • In the instance declaration for ‘Monoid (Bounds a)’
       |
    39 | instance Ord a => Monoid (Bounds a) where
       |
```

**Comment by philzook58** [comment]
I think that the latest version needs to be pushed to hackage. There are fixes for SemiGroup instances in this repo.

**Comment by jyp** [comment]
I pushed this to hackage now. Thanks!
